# ------------------------------------------------------------------------------
#  Copyright Christopher Kormanyos 2022 - 2024.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

name: gamma_f77_codecov
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  gnumake-gcc-gcov-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        standard: [ f2018 ]
        compiler: [ g++ ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: gnumake-gcc-gcov-native
        run: |
          cd .gcov/make
          echo "build and run gcov/lcov/genhtml"
          ./cover.sh
          echo
          echo "return to gamma_f77 root directory"
          cd ../..
      - name: upload-codecov
        uses: codecov/codecov-action@v4
        with:
          plugin: gcov
          file: ${{ runner.workspace }}/gamma_f77/.gcov/make/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: false
